# Generated by Django 3.2.6 on 2022-05-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityData',
            fields=[
                ('request_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField()),
                ('project_name', models.CharField(max_length=128)),
                ('data_center', models.CharField(max_length=5)),
                ('user_id', models.CharField(max_length=64)),
                ('std_stable1', models.IntegerField()),
                ('std_stable2', models.IntegerField()),
                ('std_arbor', models.IntegerField()),
                ('stable1', models.IntegerField()),
                ('stable2', models.IntegerField()),
                ('arbor', models.IntegerField()),
                ('gravit', models.IntegerField()),
                ('move_group_name', models.CharField(max_length=64)),
                ('remarks', models.CharField(max_length=256)),
                ('tkt_status', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'request_capacity_data',
            },
        ),
        migrations.CreateModel(
            name='FinanceProcurementApprovalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_center', models.CharField(max_length=128)),
                ('project_name', models.CharField(max_length=128)),
                ('group', models.CharField(max_length=128)),
                ('milestone_name', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=128)),
                ('std_stable1', models.IntegerField()),
                ('std_stable2', models.IntegerField()),
                ('std_arbor', models.IntegerField()),
                ('stable1', models.IntegerField()),
                ('stable2', models.IntegerField()),
                ('arbor', models.IntegerField()),
                ('gravit', models.IntegerField()),
                ('remarks', models.CharField(max_length=200)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=128)),
                ('request_id', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'finance_procurement_approved_data',
            },
        ),
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128)),
                ('request_id', models.CharField(max_length=128)),
                ('updated_time', models.DateTimeField()),
                ('data_center', models.CharField(max_length=5)),
                ('user_id', models.CharField(max_length=64)),
                ('std_stable1', models.IntegerField()),
                ('std_stable2', models.IntegerField()),
                ('std_arbor', models.IntegerField()),
                ('stable1', models.IntegerField()),
                ('stable2', models.IntegerField()),
                ('arbor', models.IntegerField()),
                ('gravit', models.IntegerField()),
                ('move_group_name', models.CharField(max_length=64)),
                ('remarks', models.CharField(max_length=256)),
                ('tkt_status', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'history_capacity_data',
            },
        ),
        migrations.CreateModel(
            name='MilestoneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'milestone_data',
            },
        ),
        migrations.CreateModel(
            name='ProjectPlannerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_center', models.CharField(max_length=128)),
                ('project_name', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=128)),
                ('milestone_name', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=128)),
                ('std_stable1', models.IntegerField()),
                ('std_stable2', models.IntegerField()),
                ('std_arbor', models.IntegerField()),
                ('stable1', models.IntegerField()),
                ('stable2', models.IntegerField()),
                ('arbor', models.IntegerField()),
                ('gravit', models.IntegerField()),
                ('remarks', models.CharField(max_length=200)),
                ('financial_approval', models.BooleanField()),
                ('procurement_approval', models.BooleanField()),
                ('floor_manager_approval', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'project_planner_data',
            },
        ),
        migrations.CreateModel(
            name='ProjectPlannerHistoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_center', models.CharField(max_length=128)),
                ('project_name', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=128)),
                ('milestone_name', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=128)),
                ('std_stable1', models.IntegerField()),
                ('std_stable2', models.IntegerField()),
                ('std_arbor', models.IntegerField()),
                ('stable1', models.IntegerField()),
                ('stable2', models.IntegerField()),
                ('arbor', models.IntegerField()),
                ('gravit', models.IntegerField()),
                ('remarks', models.CharField(max_length=200)),
                ('financial_approval', models.BooleanField()),
                ('procurement_approval', models.BooleanField()),
                ('floor_manager_approval', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'project_planner_history_data',
            },
        ),
    ]
